kind: Template
apiVersion: v1
labels:
  template: letsencrypt-policy-template
metadata:
  annotations:
    openshift.io/display-name: Let's Encrypt Policy Template
    description: Template for Configuring Policies for the Let's Encrypt Controller.
    tags: infrastructure,letsencrypt,controller,policy
    template.openshift.io/documentation-url: https://github.com/tnozicka/openshift-acme.git
  name: letsencrypt-policy
objects:
- kind: ClusterRole
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: ${NAME}
  rules:
  - apiGroups:
    - ""
    - "route.openshift.io"
    resources:
    - endpoints
    - endpoints/restricted
    - events
    - routes
    - routes/custom-host
    - routes/status
    - secrets
    - services
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
- kind: ClusterRoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: ${NAME}
  roleRef:
    name: ${NAME}
  subjects:
  - kind: ServiceAccount
    name: ${SERVICEACCOUNT_NAME}
    namespace: ${NAMESPACE}
  userNames:
  - system:serviceaccount:${NAMESPACE}:${SERVICEACCOUNT_NAME}
parameters:
- description: Name of the Policies
  name: NAME
  value: acme-controller
  required: true
- description: The NameSpace to Deploy to
  displayName: Namespace
  name: NAMESPACE
  required: true
- description: Name of the Application
  name: SERVICEACCOUNT_NAME
  value: acme
  required: true
