---
apiVersion: v1
kind: Template
labels:
  template: projectrequest-template
message: |-
  The following project/namespace has been created: ${NAME}
metadata:
  annotations:
    description: |-
      ProjectRequest Template
  creationTimestamp: null
  name: ${NAME}
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    name: ${NAME}
  description: '${DESCRIPTION}' 
  displayName: '${DISPLAY_NAME}'
parameters:
- description: Name
  displayName: Name
  name: NAME
  required: true
- description: DisplayName
  displayName: DisplayName
  name: DISPLAY_NAME
  required: true
- description: Description
  displayName: Description
  name: DESCRIPTION