---

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "acme-project"
    template: "{{ inventory_dir }}/../../files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../../files/acme/project/params"
- object: policy
  content:
  - name: "acme-template"
    template: "{{ inventory_dir }}/../../files/acme/policy/template.yml"
    params: "{{ inventory_dir }}/../../files/acme/policy/params"
- object: deployments
  content:
  - name: "acme-template"
    namespace: "acme"
    template: "{{ inventory_dir }}/../../files/acme/deployment/template.yml"
    params: "{{ inventory_dir }}/../../files/acme/deployment/params"
